title: Daniel Smith
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a second year student studying computer science and finishing his degree this fall semester. My favorite language is python, but 
  I know Java and MatLab as well. I enjoy working with Internet of Things (IOT) Devices, as well as robotics.
  <br>
  <br>
  Contact information:
  Email: danieljsmith1313@gmail.com


  <br>
  <br>
  <a href="www.linkedin.com/in/daniel-smith-9a2539174">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-142063093-1 # your Google Analytics tracking ID here
