title: Daniel Smith
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a second year computer science student finishing his degree online this fall semester in Scottsbluff, Nebraska.
  <br>
  Email: danieljsmith1313@gmail.com
  <br>
  <a href="www.linkedin.com/in/daniel-smith-9a2539174">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-142063093-1 # your Google Analytics tracking ID here
